### ISSUE TITLE
environment.txt doesn't work

### ISSUE THREAD

**Issue by negishubham** [SLDGroup/ZiCo#2]
Hi, 

Can you please provide a .yml file for the environment setup? Somehow "pip install -r environment.txt" doesn't work. It is giving the below error. 

ERROR: Invalid requirement: '_libgcc_mutex             0.1                 conda_forge    conda-forge' (from line 2 of environment.txt)

**Comment by LiGuihong** [comment]
Hi there,

You should use **conda** to install the environment. Sorry for not making it clear. This is because some packages are from the conda-forge channel. Could you pls try this? Feel free to let me know if you have any issue.

Best,
Guihong

**Comment by negishubham** [comment]
Hi, 

I tried running this "conda create --name zico2 --file environment.txt " command it is always giving the below error. I tried updating conda as well and even that didn't solve the issue. 

" CondaValueError: could not parse '_libgcc_mutex             0.1                 conda_forge    conda-forge' in: environment.txt

**Comment by negishubham** [comment]
Hi, 
As you can see in the above error that conda is not able to parse the provided environment file. Can you please give .yml file? You can generate the yml file using "conda env export > environment.yml" command.

**Comment by LiGuihong** [comment]
Hi,

Thanks for the great suggestion. I just updated the README file. I did a test and it works on my side. You could double-check. Let me know if it works or not.

Best,
Guihong
