### ISSUE TITLE
question about the model used for calculating the ZICO score

### ISSUE THREAD

**Issue by negishubham** [SLDGroup/ZiCo#3]
Hi, 

Why is no_create=False and no_reslink=True in the compute_ nas_score function on line 121? 
I understand that making no_reslink=True removes residual connections from the model but I don't understand why is it removed to calculate the score. 

https://github.com/SLDGroup/ZiCo/blob/b0fec65923a90e84501593f675b1e2f422d79e3d/evolution_search.py#L121

**Comment by LiGuihong** [comment]
Hi,

Sorry for the later reply. Other proxies (ZenNAS) set _no_reslink_ as _false_; hence, we also set _no_reslink_ as _False_ to make an **apple-to-apple** with other proxies. You can set it as True to do the search only if you don't want to make the comparison with other proxies. 

Best,
Guihong
